### ISSUE TITLE
ERROR: for Aparoid  Cannot start service aparoid

### ISSUE THREAD

**Issue by AmbitiousSam** [stefan2200/aparoid#3]
![Screenshot 2021-12-25 at 8 01 30 PM](https://user-images.githubusercontent.com/54389032/147387193-f59ec087-4cbf-42a4-9b41-6843ac6ad379.png)
I have this particular error coming up every time i am trying to ```docker-compose up``` 
I am on macos monterey

**Comment by stefan2200** [comment]
Hi, it looks like docker-compose did not correctly build the image because the /app directory does not exist or is empty. Can you please run the following command in the aparoid directory and check if that fixes it:
`docker-compose up --build --force-recreate aparoid`

**Comment by AmbitiousSam** [comment]
It still says the same even after changing using your mentioned command `docker-compose up --build --force-recreate aparoid`

**Comment by stefan2200** [comment]
I just checked on a Mac and everything works fine, which version of docker/docker-compose are you using?

**Comment by AmbitiousSam** [comment]
![Screenshot 2022-01-04 at 6 45 17 AM](https://user-images.githubusercontent.com/54389032/147996960-9f013f58-c151-495a-afc5-a499a9c6f0fc.png)
They are currently at this version.
I used the same commands mentioned in your Readme file.
Is it somewhere that there might be different commands for running on macOS? Could you provide me the commands run against your macOS system?

**Comment by stefan2200** [comment]
Just a `docker-compose up` did the trick. Can you run `docker build - < Dockerfile` in the Aparoid directory and see if that contains any errors.

**Comment by AmbitiousSam** [comment]
![Screenshot 2022-01-04 at 7 21 23 PM](https://user-images.githubusercontent.com/54389032/148068963-227f0c85-44df-481d-ac85-32a6eb6c0069.png)
Gives me an error

**Comment by stefan2200** [comment]
Hey, it took a while since I didn't have much time to work on this project. Could you check again with the latest release?

**Comment by AmbitiousSam** [comment]
Yes, It's now working with the latest release stefan,
Thanks for the help!!

**Comment by stefan2200** [comment]
Awesome, happy to hear that!
